import { CategoryRepo } from "./CategoryRepo.js";
import { ProductRepo } from "./ProductRepo.js";
import { CountryRepo } from "./CountryRepo.js";
import { OrderRepo } from "./OrderRepo.js";
import { PaymentInfoRepo } from "./PaymentInfoRepo.js";
import { RoleRepo } from "./RoleRepo.js";
import { ShippingAddressRepo } from "./ShippingAddressRepo.js";
import { UsersRepo } from "./UsersRepo.js";
import { Category } from "../Models/Category.js";
import { Product } from "../Models/Product.js";
import { User } from "../Models/User.js";
import { Role } from "../Models/Role.js";

export class DbRepo {
  static SeedLocalStorage() {
    localStorage.clear();
    CategoryRepo.saveCategories([
      new Category("Electronics").toJSON(),
      new Category("Clothes").toJSON(),
      new Category("Furnture").toJSON(),
      new Category("Fashion").toJSON(),
      new Category("MakeUp").toJSON(),
    ]);

    ProductRepo.saveProducts([
      new Product(
        "Samsung Galaxy S21 Ultra",
        1199.99,
        50,
        "A premium smartphone with a high-resolution camera and AMOLED display.",
        1,
        "https://example.com/images/samsung-galaxy-s21-ultra.jpg"
      ),
      new Product(
        "Apple iPhone 13 Pro Max",
        1099.99,
        40,
        "The latest iPhone with advanced camera features and improved performance.",
        1,
        "https://example.com/images/apple-iphone-13-pro-max.jpg"
      ),
      new Product(
        "Sony WH-1000XM5 Headphones",
        349.99,
        100,
        "Noise-canceling wireless headphones with superior sound quality.",
        1,
        "https://example.com/images/sony-wh-1000xm5.jpg"
      ),
      new Product(
        "HP Pavilion Gaming Laptop",
        899.99,
        30,
        "High-performance gaming laptop with dedicated graphics.",
        1,
        "https://example.com/images/hp-pavilion-gaming-laptop.jpg"
      ),
      new Product(
        "Asus ROG Zephyrus G14",
        1499.99,
        20,
        "Compact gaming laptop with powerful specifications.",
        1,
        "https://example.com/images/asus-rog-zephyrus-g14.jpg"
      ),
      new Product(
        "Nike Air Max 270",
        129.99,
        200,
        "Stylish and comfortable running shoes with a signature air unit.",
        2,
        "https://example.com/images/nike-air-max-270.jpg"
      ),
      new Product(
        "Adidas Ultraboost 22",
        159.99,
        150,
        "Performance running shoes with responsive cushioning.",
        2,
        "https://example.com/images/adidas-ultraboost-22.jpg"
      ),
      new Product(
        "Levi's 501 Original Jeans",
        59.99,
        300,
        "Classic fit jeans with timeless style.",
        2,
        "https://example.com/images/levis-501-original-jeans.jpg"
      ),
      new Product(
        "Tommy Hilfiger Polo Shirt",
        49.99,
        250,
        "Premium polo shirt with iconic logo embroidery.",
        2,
        "https://example.com/images/tommy-hilfiger-polo.jpg"
      ),
      new Product(
        "Gucci Leather Belt",
        399.99,
        100,
        "Luxury leather belt with signature Gucci design.",
        2,
        "https://example.com/images/gucci-leather-belt.jpg"
      ),
      new Product(
        "Ikea Billy Bookcase",
        79.99,
        400,
        "Versatile and affordable bookcase with adjustable shelves.",
        3,
        "https://example.com/images/ikea-billy-bookcase.jpg"
      ),
      new Product(
        "Wayfair Modern Coffee Table",
        119.99,
        150,
        "Sleek and modern coffee table for your living room.",
        3,
        "https://example.com/images/wayfair-coffee-table.jpg"
      ),
      new Product(
        "West Elm Sofa",
        899.99,
        20,
        "Comfortable and stylish sofa for modern interiors.",
        3,
        "https://example.com/images/west-elm-sofa.jpg"
      ),
      new Product(
        "Ashley Furniture Bed Frame",
        499.99,
        50,
        "Durable and elegant bed frame for a cozy bedroom.",
        3,
        "https://example.com/images/ashley-furniture-bed-frame.jpg"
      ),
      new Product(
        "Pottery Barn Dining Table",
        1099.99,
        15,
        "Elegant dining table made with high-quality materials.",
        3,
        "https://example.com/images/pottery-barn-dining-table.jpg"
      ),
      new Product(
        "MAC Lipstick Ruby Woo",
        19.99,
        500,
        "Classic red lipstick with a matte finish.",
        5,
        "https://example.com/images/mac-lipstick-ruby-woo.jpg"
      ),
      new Product(
        "Fenty Beauty Foundation",
        34.99,
        400,
        "Long-lasting foundation for all skin tones.",
        5,
        "https://example.com/images/fenty-beauty-foundation.jpg"
      ),
      new Product(
        "Maybelline Mascara",
        7.99,
        800,
        "Affordable and effective mascara for voluminous lashes.",
        5,
        "https://example.com/images/maybelline-mascara.jpg"
      ),
      new Product(
        "L'Oréal Paris Eyeliner",
        8.99,
        700,
        "Precise eyeliner for a bold look.",
        5,
        "https://example.com/images/loreal-eyeliner.jpg"
      ),
      new Product(
        "Estée Lauder Night Cream",
        79.99,
        150,
        "Rejuvenating night cream for radiant skin.",
        5,
        "https://example.com/images/estee-lauder-night-cream.jpg"
      ),
      new Product(
        "Samsung 65-inch QLED TV",
        999.99,
        30,
        "Large QLED TV with stunning picture quality.",
        1,
        "https://example.com/images/samsung-65-inch-qled.jpg"
      ),
      new Product(
        "Apple MacBook Pro 14-inch",
        1999.99,
        15,
        "High-performance laptop for professionals.",
        1,
        "https://example.com/images/macbook-pro-14.jpg"
      ),
      new Product(
        "Bose SoundLink Revolve",
        179.99,
        100,
        "Portable Bluetooth speaker with immersive sound.",
        1,
        "https://example.com/images/bose-soundlink-revolve.jpg"
      ),
      new Product(
        "Dell XPS 15 Laptop",
        1499.99,
        25,
        "Premium laptop with stunning display and power.",
        1,
        "https://example.com/images/dell-xps-15.jpg"
      ),
      new Product(
        "Fitbit Versa 4",
        229.99,
        200,
        "Advanced fitness tracker with heart rate monitoring.",
        1,
        "https://example.com/images/fitbit-versa-4.jpg"
      ),
      new Product(
        "Under Armour Running Shoes",
        89.99,
        180,
        "Durable and comfortable running shoes.",
        2,
        "https://example.com/images/under-armour-shoes.jpg"
      ),
      new Product(
        "H&M Cotton T-Shirt",
        14.99,
        600,
        "Affordable and comfortable T-shirt for everyday wear.",
        2,
        "https://example.com/images/hm-cotton-tshirt.jpg"
      ),
      new Product(
        "Zara Blazer Jacket",
        129.99,
        120,
        "Elegant blazer jacket for formal occasions.",
        2,
        "https://example.com/images/zara-blazer.jpg"
      ),
      new Product(
        "Ray-Ban Aviator Sunglasses",
        159.99,
        300,
        "Stylish aviator sunglasses with UV protection.",
        2,
        "https://example.com/images/rayban-aviator.jpg"
      ),
      new Product(
        "Louis Vuitton Wallet",
        499.99,
        50,
        "Luxury leather wallet with iconic branding.",
        2,
        "https://example.com/images/lv-wallet.jpg"
      ),
      // Add more here up to 50 products
    ]);

    RoleRepo.saveRoles([
      new Role("Admin"),
      new Role("Seller"),
      new Role("Customer"),
    ]);

    UsersRepo.saveUser([
      new User(
        "John Doe",
        "John",
        "Doe",
        1234567,
        "john.doe@example.com",
        1,
        "password123",
        new UserAddress("123 Main St", "New York", "NY", 10001, "U.S.A"),
        "https://example.com/img/john.jpg"
      ),
      new User(
        "Jane Smith",
        "Jane",
        "Smith",
        9876543,
        "jane.smith@example.com",
        2,
        "securepass",
        new UserAddress("456 Elm St", "Los Angeles", "CA", 90001, "U.S.A"),
        "https://example.com/img/jane.jpg"
      ),
      new User(
        "Mike Johnson",
        "Mike",
        "Johnson",
        5678901,
        "mike.johnson@example.com",
        3,
        "mypassword",
        new UserAddress("789 Pine St", "Chicago", "IL", 60601, "U.S.A"),
        "https://example.com/img/mike.jpg"
      ),
      new User(
        "Emily Davis",
        "Emily",
        "Davis",
        2345678,
        "emily.davis@example.com",
        1,
        "emilypass",
        new UserAddress("101 Oak St", "Houston", "TX", 77001, "U.S.A"),
        "https://example.com/img/emily.jpg"
      ),
      new User(
        "Chris Brown",
        "Chris",
        "Brown",
        3456789,
        "chris.brown@example.com",
        2,
        "chrispassword",
        new UserAddress("202 Maple St", "Phoenix", "AZ", 85001, "U.S.A"),
        "https://example.com/img/chris.jpg"
      ),
      new User(
        "Sophia Wilson",
        "Sophia",
        "Wilson",
        8765432,
        "sophia.wilson@example.com",
        3,
        "sophiapass",
        new UserAddress("303 Birch St", "Philadelphia", "PA", 19101, "U.S.A"),
        "https://example.com/img/sophia.jpg"
      ),
      new User(
        "David Martinez",
        "David",
        "Martinez",
        4567890,
        "david.martinez@example.com",
        1,
        "davidpass",
        new UserAddress("404 Cedar St", "San Antonio", "TX", 78201, "U.S.A"),
        "https://example.com/img/david.jpg"
      ),
      new User(
        "Olivia Garcia",
        "Olivia",
        "Garcia",
        3456789,
        "olivia.garcia@example.com",
        2,
        "oliviapass",
        new UserAddress("505 Walnut St", "San Diego", "CA", 92101, "U.S.A"),
        "https://example.com/img/olivia.jpg"
      ),
      new User(
        "Daniel Thomas",
        "Daniel",
        "Thomas",
        2345678,
        "daniel.thomas@example.com",
        3,
        "danielpass",
        new UserAddress("606 Cherry St", "Dallas", "TX", 75201, "U.S.A"),
        "https://example.com/img/daniel.jpg"
      ),
      new User(
        "Isabella Lee",
        "Isabella",
        "Lee",
        1234567,
        "isabella.lee@example.com",
        1,
        "isabellapass",
        new UserAddress("707 Spruce St", "Austin", "TX", 73301, "U.S.A"),
        "https://example.com/img/isabella.jpg"
      ),
    ]);

    let countriesJson = [
      { name: "Afghanistan", code: "AF" },
      { name: "Åland Islands", code: "AX" },
      { name: "Albania", code: "AL" },
      { name: "Algeria", code: "DZ" },
      { name: "American Samoa", code: "AS" },
      { name: "AndorrA", code: "AD" },
      { name: "Angola", code: "AO" },
      { name: "Anguilla", code: "AI" },
      { name: "Antarctica", code: "AQ" },
      { name: "Antigua and Barbuda", code: "AG" },
      { name: "Argentina", code: "AR" },
      { name: "Armenia", code: "AM" },
      { name: "Aruba", code: "AW" },
      { name: "Australia", code: "AU" },
      { name: "Austria", code: "AT" },
      { name: "Azerbaijan", code: "AZ" },
      { name: "Bahamas", code: "BS" },
      { name: "Bahrain", code: "BH" },
      { name: "Bangladesh", code: "BD" },
      { name: "Barbados", code: "BB" },
      { name: "Belarus", code: "BY" },
      { name: "Belgium", code: "BE" },
      { name: "Belize", code: "BZ" },
      { name: "Benin", code: "BJ" },
      { name: "Bermuda", code: "BM" },
      { name: "Bhutan", code: "BT" },
      { name: "Bolivia", code: "BO" },
      { name: "Bosnia and Herzegovina", code: "BA" },
      { name: "Botswana", code: "BW" },
      { name: "Bouvet Island", code: "BV" },
      { name: "Brazil", code: "BR" },
      { name: "British Indian Ocean Territory", code: "IO" },
      { name: "Brunei Darussalam", code: "BN" },
      { name: "Bulgaria", code: "BG" },
      { name: "Burkina Faso", code: "BF" },
      { name: "Burundi", code: "BI" },
      { name: "Cambodia", code: "KH" },
      { name: "Cameroon", code: "CM" },
      { name: "Canada", code: "CA" },
      { name: "Cape Verde", code: "CV" },
      { name: "Cayman Islands", code: "KY" },
      { name: "Central African Republic", code: "CF" },
      { name: "Chad", code: "TD" },
      { name: "Chile", code: "CL" },
      { name: "China", code: "CN" },
      { name: "Christmas Island", code: "CX" },
      { name: "Cocos (Keeling) Islands", code: "CC" },
      { name: "Colombia", code: "CO" },
      { name: "Comoros", code: "KM" },
      { name: "Congo", code: "CG" },
      { name: "Congo, The Democratic Republic of the", code: "CD" },
      { name: "Cook Islands", code: "CK" },
      { name: "Costa Rica", code: "CR" },
      { name: "Cote D'Ivoire", code: "CI" },
      { name: "Croatia", code: "HR" },
      { name: "Cuba", code: "CU" },
      { name: "Cyprus", code: "CY" },
      { name: "Czech Republic", code: "CZ" },
      { name: "Denmark", code: "DK" },
      { name: "Djibouti", code: "DJ" },
      { name: "Dominica", code: "DM" },
      { name: "Dominican Republic", code: "DO" },
      { name: "Ecuador", code: "EC" },
      { name: "Egypt", code: "EG" },
      { name: "El Salvador", code: "SV" },
      { name: "Equatorial Guinea", code: "GQ" },
      { name: "Eritrea", code: "ER" },
      { name: "Estonia", code: "EE" },
      { name: "Ethiopia", code: "ET" },
      { name: "Falkland Islands (Malvinas)", code: "FK" },
      { name: "Faroe Islands", code: "FO" },
      { name: "Fiji", code: "FJ" },
      { name: "Finland", code: "FI" },
      { name: "France", code: "FR" },
      { name: "French Guiana", code: "GF" },
      { name: "French Polynesia", code: "PF" },
      { name: "French Southern Territories", code: "TF" },
      { name: "Gabon", code: "GA" },
      { name: "Gambia", code: "GM" },
      { name: "Georgia", code: "GE" },
      { name: "Germany", code: "DE" },
      { name: "Ghana", code: "GH" },
      { name: "Gibraltar", code: "GI" },
      { name: "Greece", code: "GR" },
      { name: "Greenland", code: "GL" },
      { name: "Grenada", code: "GD" },
      { name: "Guadeloupe", code: "GP" },
      { name: "Guam", code: "GU" },
      { name: "Guatemala", code: "GT" },
      { name: "Guernsey", code: "GG" },
      { name: "Guinea", code: "GN" },
      { name: "Guinea-Bissau", code: "GW" },
      { name: "Guyana", code: "GY" },
      { name: "Haiti", code: "HT" },
      { name: "Heard Island and Mcdonald Islands", code: "HM" },
      { name: "Holy See (Vatican City State)", code: "VA" },
      { name: "Honduras", code: "HN" },
      { name: "Hong Kong", code: "HK" },
      { name: "Hungary", code: "HU" },
      { name: "Iceland", code: "IS" },
      { name: "India", code: "IN" },
      { name: "Indonesia", code: "ID" },
      { name: "Iran, Islamic Republic Of", code: "IR" },
      { name: "Iraq", code: "IQ" },
      { name: "Ireland", code: "IE" },
      { name: "Isle of Man", code: "IM" },
      { name: "Israel", code: "IL" },
      { name: "Italy", code: "IT" },
      { name: "Jamaica", code: "JM" },
      { name: "Japan", code: "JP" },
      { name: "Jersey", code: "JE" },
      { name: "Jordan", code: "JO" },
      { name: "Kazakhstan", code: "KZ" },
      { name: "Kenya", code: "KE" },
      { name: "Kiribati", code: "KI" },
      { name: "Korea, Democratic People'S Republic of", code: "KP" },
      { name: "Korea, Republic of", code: "KR" },
      { name: "Kuwait", code: "KW" },
      { name: "Kyrgyzstan", code: "KG" },
      { name: "Lao People'S Democratic Republic", code: "LA" },
      { name: "Latvia", code: "LV" },
      { name: "Lebanon", code: "LB" },
      { name: "Lesotho", code: "LS" },
      { name: "Liberia", code: "LR" },
      { name: "Libyan Arab Jamahiriya", code: "LY" },
      { name: "Liechtenstein", code: "LI" },
      { name: "Lithuania", code: "LT" },
      { name: "Luxembourg", code: "LU" },
      { name: "Macao", code: "MO" },
      { name: "Macedonia, The Former Yugoslav Republic of", code: "MK" },
      { name: "Madagascar", code: "MG" },
      { name: "Malawi", code: "MW" },
      { name: "Malaysia", code: "MY" },
      { name: "Maldives", code: "MV" },
      { name: "Mali", code: "ML" },
      { name: "Malta", code: "MT" },
      { name: "Marshall Islands", code: "MH" },
      { name: "Martinique", code: "MQ" },
      { name: "Mauritania", code: "MR" },
      { name: "Mauritius", code: "MU" },
      { name: "Mayotte", code: "YT" },
      { name: "Mexico", code: "MX" },
      { name: "Micronesia, Federated States of", code: "FM" },
      { name: "Moldova, Republic of", code: "MD" },
      { name: "Monaco", code: "MC" },
      { name: "Mongolia", code: "MN" },
      { name: "Montserrat", code: "MS" },
      { name: "Morocco", code: "MA" },
      { name: "Mozambique", code: "MZ" },
      { name: "Myanmar", code: "MM" },
      { name: "Namibia", code: "NA" },
      { name: "Nauru", code: "NR" },
      { name: "Nepal", code: "NP" },
      { name: "Netherlands", code: "NL" },
      { name: "Netherlands Antilles", code: "AN" },
      { name: "New Caledonia", code: "NC" },
      { name: "New Zealand", code: "NZ" },
      { name: "Nicaragua", code: "NI" },
      { name: "Niger", code: "NE" },
      { name: "Nigeria", code: "NG" },
      { name: "Niue", code: "NU" },
      { name: "Norfolk Island", code: "NF" },
      { name: "Northern Mariana Islands", code: "MP" },
      { name: "Norway", code: "NO" },
      { name: "Oman", code: "OM" },
      { name: "Pakistan", code: "PK" },
      { name: "Palau", code: "PW" },
      { name: "Palestinian Territory, Occupied", code: "PS" },
      { name: "Panama", code: "PA" },
      { name: "Papua New Guinea", code: "PG" },
      { name: "Paraguay", code: "PY" },
      { name: "Peru", code: "PE" },
      { name: "Philippines", code: "PH" },
      { name: "Pitcairn", code: "PN" },
      { name: "Poland", code: "PL" },
      { name: "Portugal", code: "PT" },
      { name: "Puerto Rico", code: "PR" },
      { name: "Qatar", code: "QA" },
      { name: "Reunion", code: "RE" },
      { name: "Romania", code: "RO" },
      { name: "Russian Federation", code: "RU" },
      { name: "RWANDA", code: "RW" },
      { name: "Saint Helena", code: "SH" },
      { name: "Saint Kitts and Nevis", code: "KN" },
      { name: "Saint Lucia", code: "LC" },
      { name: "Saint Pierre and Miquelon", code: "PM" },
      { name: "Saint Vincent and the Grenadines", code: "VC" },
      { name: "Samoa", code: "WS" },
      { name: "San Marino", code: "SM" },
      { name: "Sao Tome and Principe", code: "ST" },
      { name: "Saudi Arabia", code: "SA" },
      { name: "Senegal", code: "SN" },
      { name: "Serbia and Montenegro", code: "CS" },
      { name: "Seychelles", code: "SC" },
      { name: "Sierra Leone", code: "SL" },
      { name: "Singapore", code: "SG" },
      { name: "Slovakia", code: "SK" },
      { name: "Slovenia", code: "SI" },
      { name: "Solomon Islands", code: "SB" },
      { name: "Somalia", code: "SO" },
      { name: "South Africa", code: "ZA" },
      { name: "South Georgia and the South Sandwich Islands", code: "GS" },
      { name: "Spain", code: "ES" },
      { name: "Sri Lanka", code: "LK" },
      { name: "Sudan", code: "SD" },
      { name: "Suriname", code: "SR" },
      { name: "Svalbard and Jan Mayen", code: "SJ" },
      { name: "Swaziland", code: "SZ" },
      { name: "Sweden", code: "SE" },
      { name: "Switzerland", code: "CH" },
      { name: "Syrian Arab Republic", code: "SY" },
      { name: "Taiwan, Province of China", code: "TW" },
      { name: "Tajikistan", code: "TJ" },
      { name: "Tanzania, United Republic of", code: "TZ" },
      { name: "Thailand", code: "TH" },
      { name: "Timor-Leste", code: "TL" },
      { name: "Togo", code: "TG" },
      { name: "Tokelau", code: "TK" },
      { name: "Tonga", code: "TO" },
      { name: "Trinidad and Tobago", code: "TT" },
      { name: "Tunisia", code: "TN" },
      { name: "Turkey", code: "TR" },
      { name: "Turkmenistan", code: "TM" },
      { name: "Turks and Caicos Islands", code: "TC" },
      { name: "Tuvalu", code: "TV" },
      { name: "Uganda", code: "UG" },
      { name: "Ukraine", code: "UA" },
      { name: "United Arab Emirates", code: "AE" },
      { name: "United Kingdom", code: "GB" },
      { name: "United States", code: "US" },
      { name: "United States Minor Outlying Islands", code: "UM" },
      { name: "Uruguay", code: "UY" },
      { name: "Uzbekistan", code: "UZ" },
      { name: "Vanuatu", code: "VU" },
      { name: "Venezuela", code: "VE" },
      { name: "Viet Nam", code: "VN" },
      { name: "Virgin Islands, British", code: "VG" },
      { name: "Virgin Islands, U.S.", code: "VI" },
      { name: "Wallis and Futuna", code: "WF" },
      { name: "Western Sahara", code: "EH" },
      { name: "Yemen", code: "YE" },
      { name: "Zambia", code: "ZM" },
      { name: "Zimbabwe", code: "ZW" },
    ];
    // Convert countries data to an array of Country instances
    const countriesArray = countriesData.map(
      (data) => new Country(data["name"], data["code"])
    );

    // Save the array of Country instances
    CountryRepo.saveCountries(countriesArray);
  }
}
